# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e46ea05a97f6dc84fe4c7a2b9d79a2bb26fcb6268c7ee2a2d6ca875ec0cb7f60352d949a2c8da73ea095ff95dd451eae20723448ed1b7d748b3234348dda09

test:
  secret_key_base: 037285b1f11cb1a25e30950a41fb5e833d420dfea268024d5a87b2ff12713d2c33aa302fc1032bc702901b03ea86c77eba9938c3fc1adbcb8a079890374b1583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
